server.port: 9100
#server.servlet.context-path: /userservice
server:
  forward-headers-strategy: framework

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        #generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 4
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  jackson:
    serialization:
      fail-on-empty-beans: false

---

spring:
  config:
    activate:
      on-profile: prod
#  zipkin:
#    base-url: http://zipkin-service:9411

#  datasource:
#    url: jdbc:postgresql://kube-master1.otd4.vkrs:31167/udp
#    username: udp
#    password: udp

keycloak:
  realm: repiton
  auth-server-url: https://keycloak.repiton.dev.realityfamily.ru:9043/auth
  ssl-required: external
  public-client: true
  #keycloak resource is the client ID
  resource: admin-cli
  use-resource-role-mappings: true
  #The line below will prevent redirect to login page
  bearer-only: true
  connection-timeout: 6000
  credentials:
    secret: OSwOhFtSREU1R3kOtz4WYrbdhdu9ZW5G


logging:
  level:
    ru:
      udp: DEBUG
    org:
      apache:
        http: DEBUG
      springframework:
        web:
          servlet:
            mvc: DEBUG
          client:
            RestTemplate: DEBUG
        security: DEBUG
        jdbc:
          core:
            StatementCreatorUtils: DEBUG
            JdbcTemplate: DEBUG
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss
---

spring:
  config:
    activate:
      on-profile: dev

#  datasource:
#    url: jdbc:postgresql://localhost:5432/userservice
#    username: postgres
#    password: mysecretpassword
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

#keycloak:
#  api:
#    url: http://localhost:8085/auth/


keycloak:
  realm: repiton
  auth-server-url: http://localhost:8085/auth
  ssl-required: external
  public-client: true
  #keycloak resource is the client ID
  resource: admin-cli
  use-resource-role-mappings: true
  #The line below will prevent redirect to login page
  bearer-only: true
  connection-timeout: 6000
  credentials:
    secret: r486NQgMRmlcJyzwYXH6aQxww52uvery


logging:
  level:
    ru:
      udp: DEBUG
    org:
      apache:
        http: DEBUG
      springframework:
        web:
          servlet:
            mvc: DEBUG
          client:
            RestTemplate: DEBUG
        security: DEBUG
        jdbc:
          core:
            StatementCreatorUtils: DEBUG
            JdbcTemplate: DEBUG
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss

---

spring:
  config:
    activate:
      on-profile: devLaba

  #  datasource:
  #    url: jdbc:postgresql://localhost:5432/userservice
  #    username: postgres
  #    password: mysecretpassword
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

#keycloak:
#  api:
#    url: http://localhost:8085/auth/


keycloak:
  realm: repiton
  auth-server-url: https://keycloak.repiton.dev.realityfamily.ru:9043/auth
  ssl-required: external
  public-client: true
  #keycloak resource is the client ID
  resource: admin-cli
  use-resource-role-mappings: true
  #The line below will prevent redirect to login page
  bearer-only: true
  connection-timeout: 6000
  credentials:
    secret: OSwOhFtSREU1R3kOtz4WYrbdhdu9ZW5G


logging:
  level:
    ru:
      udp: DEBUG
    org:
      apache:
        http: DEBUG
      springframework:
        web:
          servlet:
            mvc: DEBUG
          client:
            RestTemplate: DEBUG
        security: DEBUG
        jdbc:
          core:
            StatementCreatorUtils: DEBUG
            JdbcTemplate: DEBUG
  pattern:
    dateformat: dd-MM-yyyy HH:mm:ss
